### PR TITLE
Fixing the fast generation

### PR DESCRIPTION
**Pull request by Zeta36**
I think I found the problem with the fast generation. Problem probably was in a bug in this line in the _generator_dilation_layer() method:

conv_gate = output_gate + variables['gate_bias']

That it should be:

output_gate = output_gate + variables['gate_bias']

So, everyone that has used the bias parameter as True, has been generating noise for a long time. I test with the image generation (#125) and now all was fine with the fine fast generation (no different outputs between fast and standard generation).

### CODE REVIEW

**Comment by Zeta36** [comment]
Ops! Please, do not merge the binary file I uploaded in my fork. Just the update in the model.py file  (53ad718).

**Comment by nakosung** [comment]
I posted a *cleaned* version as #127.

**Comment by ibab** [comment]
@Zeta36: Should I go ahead and merge #127 or do you want to remove the `.wav` file from this PR?

**Comment by Zeta36** [comment]
@ibab I don't mind, you can go ahead with #127. Actually, I don't really know how to remove the .wav file from this pull request :P.

**Comment by ibab** [comment]
Okay :)
Thanks a lot for fixing this!
I'm not sure why this problem didn't cause the unit tests to fail.

**Comment by lemonzi** [comment]
There is a test for training with a sine wave and overfitting and a test
for generating white noise with an untrained net and doing size and range
checks. We should add a test that generates a sine wave with an overfitted
net to close the loop :)

El dv., 7 oct. 2016 a les 14:43, Igor Babuschkin (<notifications@github.com>)
va escriure:

**Comment by jyegerlehner** [comment]
Thanks @Zeta36 for finding that and the fix! I confirm that it works.

**Comment by Zeta36** [comment]
You are welcome @jyegerlehner :)

**Pull request closed without merging**
