### PR TITLE
Set the silence trimming threshold in generate.py

### PR DESCRIPTION
**Pull request by lemonzi**

### CODE REVIEW

**Comment by lemonzi** [comment]
Fixes #139.

**Comment by jyegerlehner** [comment]
LGTM

**Comment by pineking** [comment]
LGTM

**Comment by jyegerlehner** [comment]
@pineking  You can vote if you want to merge. It doesn't get merged until we've got at least three votes. (hint, hint). Or ibab or someone merges it anyway.  Maybe just upvote the original post?

**Comment by pineking** [comment]
@jyegerlehner Done

**Comment by ibab** [comment]
Okay, I'll go ahead and merge it.

**Pull request merged**
