### PR TITLE
Do Not Merge - fp16 experiment

### PR DESCRIPTION
**Pull request by jyegerlehner**
I just want to see what the CI server will do when we ask it to run an 16-bit floating point op. I expect it will fail, since there's no (good) way to do fp16 on the CPU.

It runs on my Maxwell GPU though, btw. You can see the loss of significant digits if you run with float16 vs float32.

### CODE REVIEW

**Comment by jyegerlehner** [comment]
How about that. It passes. So maybe the Travis CI machines have GPUs? I don't know.

**Comment by ibab** [comment]
@jyegerlehner: `float16` can be emulated on the CPU. For example, this is how `float16` works in numpy. TensorFlow also seems to be able to deal with it. It's not faster, though.

**Comment by jyegerlehner** [comment]
@ibab Right, I know it's not faster in terms of raw flops on a GPU (unless it's Pascal GP100). THere is overhead in that on Maxwell and below the fp16 has to be promoted to fp32 before arithmetic. It's conceivable there could be some speed benefit due to lower memory bandwidth requirements as many ops are bottlenecked by memory latency and bandwidth. 

My motivation for using it would be to reduce the memory footprint of the tensors in half. I expect to do some things that may push the limits of available memory and fp16 would be a bit benefit for that.

**Comment by ibab** [comment]
@jyegerlehner: Sorry, I mean it's not faster when using the CPU.
fp16 is definitely useful if your GPU supports it 👍

Unrelated to this, we could also attempt to evaluate multiple batches on multiple GPUs to speed things up for people who have them.

**Pull request closed without merging**
