### PR TITLE
Direct wav file output from command line

### PR DESCRIPTION
**Pull request by mecab**
This PR enable the users to have the result directly from command line.
Includes README updates (welcome to fix the writing)

### CODE REVIEW

**Comment by adroit91** [comment]
Are you even able to generate audio from generated models? There's an issue being discussed about that not working! [https://github.com/ibab/tensorflow-wavenet/issues/13](url)

**Comment by ibab** [comment]
Yeah, we need to fix #13 first, then I can merge this.
Theoretically, we could also use the TensorFlow ffmpeg module to save the files, but I'm fine with using `scipy`.

**Comment by mecab** [comment]
I managed to have a "valid" wav file by letting `dilations` be `1` as had mentioned by @ibab (https://github.com/ibab/tensorflow-wavenet/issues/13#issuecomment-247456622)
and avoiding to use GPU in generation to avoid `CUDA_ERROR_ILLEGAL_ADDRESS`.  But it was almost white-noise. I'm not sure whether the result was wrong or the iteration was not enough.

I agree to merge this after fixing #13.

**Comment by ibab** [comment]
@mecab: I've just found the origin of the `CUDA_ERROR_ILLEGAL_ADDRESS` bug, so generating audio files should work in a moment.
What was the loss that you managed to reach before generating?

**Comment by mecab** [comment]
Yes. We can use TensorFlow's FFmpeg. But it makes the dependency outside python (i.e., we need to install FFmpeg). In some shared computational environment, installing FFmpeg to the machine without `sudo` could be a pain.

So I'm for to use `scipy` (or other closed-in-python module) to handling audio, but it's up to you.

**Comment by mecab** [comment]
@ibab 
Super! I'm looking forward to seeing it.
The loss was almost 3, but I used custom dataset so I'm not sure it can be a good reference...

**Comment by ibab** [comment]
Duh, I thought that the bug was a missing colon in the line that crops the previously generated waveform to a smaller window, but it seems to be something else and both errors just happened to be triggered at 256 elements.

**Comment by ibab** [comment]
As audio generating is working properly now, I'll go ahead and merge this.
Thanks a lot for adding this feature!

**Pull request merged**
