### PR TITLE
Rmsprop optimizer

### PR DESCRIPTION
**Pull request by jyegerlehner**
Supercedes [PR 120](https://github.com/ibab/tensorflow-wavenet/pull/120).

### CODE REVIEW

**Comment by lemonzi** [comment]
I'd prefer a cleaner alternative to those globals, but we can merge it now and fix it later.

**Comment by jyegerlehner** [comment]
Oops right, sorry. You commented about that and then I forgot.

Is this commit something like what you had in mind?

**Comment by lemonzi** [comment]
Yes, this is great! Can you add it to the test as well?

**Comment by jyegerlehner** [comment]
Just for you @lemonzi, it is done!

**Comment by ibab** [comment]
This looks good. I'll go ahead and merge it.

**Pull request merged**
