### PR TITLE
Cast output for workaround of CUDA_ERROR_ILLEGAL_ADDRESS in generation

### PR DESCRIPTION
**Pull request by mecab**
Workaround of #13

### CODE REVIEW

**Comment by mecab** [comment]
Fixes #13

**Comment by ibab** [comment]
Cool, could you add a comment explaining that this is a workaround?

**Comment by mecab** [comment]
Right. It is actually not a fix...

Fixed the comment. Could you review?

**Comment by ibab** [comment]
Thanks 🎉

**Pull request merged**
