### PR TITLE
Make adam more stable

### PR DESCRIPTION
**Pull request by jyegerlehner**
This is on top of the RMS-prop PR. The changes unique to this PR start at the comment "Make adam more stable". 

I describe the rationale for this change in the [issue 143](https://github.com/ibab/tensorflow-wavenet/issues/143) thread.

### CODE REVIEW

**Comment by ibab** [comment]
This is excellent. I didn't even know about the `epsilon` parameter.
Unfortunately we can't merge as I've squashed your previous PR before merging it into master.
You can update your PR like this (no need to make a new one):
```
# Make sure that we have the newest changes on master
git checkout master
git pull
# Make a new branch
git checkout -b make-adam-stable-2
# Add the last commit from this PR
git cherry-pick 98783e5
# Overwrite this PR by running
git push -f origin make-adam-stable-2:make-adam-stable
```

**Comment by nakosung** [comment]
I think it would be much safer if we amplify loss instead of decreased
epsilon. (Fp16)

2016년 10월 14일 (금) 오전 3:29, Igor Babuschkin <notifications@github.com>님이 작성:

**Comment by jyegerlehner** [comment]
@nakosung  I don't think I understand what you are proposing. Could you elaborate a bit please? I think we increased, not decreased, epsilon.

**Comment by nakosung** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/adam.py#L63
says it is not good default value in general. I didn't read the code and
thought it would be safe to feed trainer with healthy range but I think I
was wrong. ;)

2016. 10. 14. 오전 9:33에 "jyegerlehner" <notifications@github.com>님이 작성:

**Comment by jyegerlehner** [comment]
Nice find on comment about epsilon. I missed that. It's surprising they buried it there, and don't mention it where everyone would see it (in the API docs).

**Comment by ibab** [comment]
This looks good, merging now.

**Pull request merged**
