### PR TITLE
Rmsprop optimizer

### PR DESCRIPTION
**Pull request by jyegerlehner**
DeepMind is using RMS prop in [Video Pixel Networks](https://arxiv.org/pdf/1610.00527v1.pdf)  as nakosung pointed out over [there](https://github.com/ibab/tensorflow-wavenet/issues/77). Video Pixel Networks are related to Wavenet.

I figured I would try RMS prop out and see if a miracle ensues.

### CODE REVIEW

**Comment by lemonzi** [comment]
Does it help? 

It would be nice to have a more generic optimizer selector rather than all these hardcoded constants. How about a dictionary that maps names to functions, and the argument parser is given its `.keys()`? I don't know what to do with the momentum though. Maybe we need a separate function or class that handles this. Or, at least, WaveNet could export a list with the supported optimizers rather than read the individual globals from the outside.

**Comment by lemonzi** [comment]
This is on top of #107, right?

**Comment by jyegerlehner** [comment]
Yes, on top of 107.

>  more generic optimizer selector rather than all these hardcoded constants. How about a dictionary

Yes, that's a better idea.

**Comment by jyegerlehner** [comment]
> Does it help? 

I haven't started running it yet. I thought I could just switch the optimizer and resume training. But it fails to load the checkpoint because there are tensors specific to the optimizer it tries to load and can't find. I think we must be saving more than just the trainable vars in our checkpoints. Is that intended, or can we change that?

**Comment by jyegerlehner** [comment]
Here's comparison training on speaker p280. Orange line is SGD (learn rate = 0.01, momentum = 0.9), aqua is adam (learn rate = 0.001), purple is RMS Prop (learn rate = 0.001, momentum=0.9).

screenshot from 2016-10-07 00 25 47

**Comment by lemonzi** [comment]
There's something wrong with the diff, it looks like your branch undoes PR's that have already been applied and then it re-applies them. If will not have any effect because of the squash, but it makes it hard to see the changes. Could you try to fix it? I believe this is GitHub's fault, for being too smart with the squash merges. You may have to undo your internal merge, rebase the old branch to the current master, and merge again.

**Comment by ccienfall** [comment]
@jyegerlehner, have Deep mind or others open the Video Pixel Networks' source codes? Recently I am reading this paper. Thanks.

**Comment by jyegerlehner** [comment]
@ccienfall Not as far as I know.

**Pull request closed without merging**
