### PR TITLE
Fix sampling rate

### PR DESCRIPTION
**Pull request by mecab**
1 << 13 == 8192
1 << 14 == 16384

Sorry if my understand is wrong... (maybe it is because of caring left and right channels so 8192 *2 ?)

### CODE REVIEW

**Comment by lemonzi** [comment]
Now that you mention this, I think the standard is 16000, not 16384, isn't it?

**Comment by ibab** [comment]
Setting the sampling rate to 16000 per second is a good idea when trying to reproduce the paper exactly.
@mecab: Could you change the value to 16000?

**Comment by widdakay** [comment]
The dataset is recorded at 48khz, as mentioned here: http://homepages.inf.ed.ac.uk/jyamagis/page3/page58/page58.html

This also is consistent with the naming of "wav48"

**Comment by mecab** [comment]
@ibab 
Sure. I'll make the change for 16000.

@widakkay
Ofcourse 48kHz has better sound, but it will possibly take much longer time to compute, and I doubt it will not improve generated ones' quality comparing the cost paid to process 48kHz.

How about leaving it 16kHz as default, and adding an arguments to allow user to customize the sampling rate?

**Comment by widdakay** [comment]
I somehow missed that this was not setting the sample rate for the file to be decoded at, and rather the sample rate to decimate them too. If it was the opposite, it would result in much slowed down audio. I just checked the documentation, and it does seem to have that effect.

**Comment by mecab** [comment]
I found it has been fixed in 5dbc007 by moving some parameters include this into external files. 🎉 
I'll close the PR.

**Pull request closed without merging**
